version: "3"

services:
  auction:
    build: 
      context: ./auction
      dockerfile: Dockerfile
    command: gunicorn --chdir auction -c auction/gconfig.py src.app:app --reload
    volumes:
      - .:/app
    env_file:
      - ./auction/env.example
    ports:
      - 5000:80
    restart: always

  bid:
    build: 
      context: ./bid
      dockerfile: Dockerfile
    command: gunicorn --chdir bid -c bid/gconfig.py src.app:app --reload
    volumes:
      - .:/app
    env_file:
      - ./bid/env.example
    ports:
      - 5001:80
    restart: always

  locustio:
    build: 
      context: ./locustio
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    env_file:
      - ./locustio/env.example
    environment:
      QTD_ITEMS: 10

  elasticsearch:
    image: elasticsearch:7.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:7.1.1
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
    volumes:
      - ./apm-server.yml:/etc/apm-server/apm-server.yml
